# ELE-32 Lab 1 - Implementação própria

In [11]:
import numpy as np
from ts_encoder import TSEncoder
from bsc_channel import BSCChannel
from ts_decoder import TSDecoder
from utils import *

message = np.array([0, 0, 1, 0, 0, 1, 1, 1, 0])

encoder = TSEncoder()
channel = BSCChannel(0.05)
decoder = TSDecoder()

encoded = encoder.encode(message)
received = channel.change_bits(encoded)
decoded = decoder.decode(received)


print(encoded)
print(received)
print(decoded)

[0 0 1 0 0 1 1 1 0 0 0 1 1 0 0 0 0]
[0 0 0 0 0 1 1 1 0 0 0 1 1 0 0 0 0]
[0 0 1 0 0 1 1 1 0]


In [3]:
78%31

16